name: Package - Web - Deploy

on:
  push:
    branches:
      - main
    paths:
      - "./packages/senate-web/**"

env:
  AWS_REGION: eu-west-1
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_DEV_DEPLOY_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_DEV_DEPLOY_ACCESS_SECRET }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/senate-web
    steps:
      - name: 'Checking out from GitHub'
        uses: 'actions/checkout@v2'

      - name: Configure node and npm
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14

      - name: install
        run: npm ci

      - name: deploy
        run: npm run cdk:deploy
