name: Package - Web - Deploy

on:
  push:
    branches:
      - main
    paths:
      - "packages/senate-web/**"

env:
  AWS_DEFAULT_REGION: eu-west-1
  AWS_REGION: eu-west-1
  AWS_ACCOUNT_ID: 477948800870
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/senate-web
    steps:
      - name: 'Checking out from GitHub'
        uses: 'actions/checkout@v2'

      - name: Configure node and npm
        uses: actions/setup-node@v2-beta
        with:
          node-version: 14

      - name: Install
        run: npm ci

      - name: build
        run: npm run build

      - name: Deploy
        run: npm run cdk:deploy

      - name: Invalidate cloudfront distribution
        run: aws cloudfront create-invalidation --distribution-id E1J7HHT6UCYNP8 --paths '/*'